import React, { useState, useEffect } from 'react';
import AlertRoutingService from '../services/AlertRoutingService';
import { getApiBaseUrl } from '../services/runtimeConfig';
import { FaExclamationTriangle, FaMapMarkerAlt, FaPhone, FaClock, FaShareAlt, FaBell, FaEye, FaRoute, FaShieldAlt, FaBuilding, FaUsers, FaAmbulance, FaFire, FaHospital } from 'react-icons/fa';

function AmberAlerts({ user, onLogout, onNavigate }) {
  const [alerts, setAlerts] = useState([]);
  const [activeAlert, setActiveAlert] = useState(null);
  const [showMap, setShowMap] = useState(false);
  const [alertRadius, setAlertRadius] = useState(5); // km
  const [notifications, setNotifications] = useState(true);
  const [routingService] = useState(new AlertRoutingService());
  const [routingAnalysis, setRoutingAnalysis] = useState(null);
  const [showRouting, setShowRouting] = useState(false);

  const [alertsLoading, setAlertsLoading] = useState(true);
  const [alertsError, setAlertsError] = useState("");
  const [flashMsg, setFlashMsg] = useState('');

  const flash = (msg) => {
    setFlashMsg(msg);
    setTimeout(() => setFlashMsg(''), 4000);
  };

  useEffect(() => {
    // Load REAL critical field reports from the persisted feed. Official
    // emergency alerts are NOT generated by EcoNet — no trusted external
    // emergency source is integrated, so absent real critical reports the UI
    // shows an honest empty state rather than a fabricated alert.
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch(`${getApiBaseUrl()}/reports/feed`, { headers: { Accept: 'application/json' } });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const reports = await res.json();
        const list = Array.isArray(reports) ? reports : [];
        const critical = list
          .filter(r => ['Critical', 'High'].includes(r.severity) || r.postStatus === 'critical')
          .map(r => ({
            id: r._id || r.id,
            type: 'environmental',
            severity: (r.severity || 'medium').toLowerCase(),
            title: r.title || `${r.category || 'Environmental'} report — ${r.location?.text || 'location unconfirmed'}`,
            description: r.content || r.description || '',
            location: r.location?.text || 'Location not confirmed',
            coordinates: r.location?.coordinates
              ? { lng: r.location.coordinates[0], lat: r.location.coordinates[1] }
              : null,
            lastSeen: r.createdAt,
            reportedBy: r.user?.name || 'EcoNet field reporter',
            contact: r.contact && typeof r.contact === 'object'
              ? {
                  phone: r.contact.phone || 'Emergency line: 112',
                  email: r.contact.email || 'Not provided',
                }
              : { phone: 'Emergency line: 112', email: 'Not provided' },
            status: r.status || 'reported',
            radius: 10,
            image: Array.isArray(r.images) && r.images.length ? r.images[0] : null,
            trustScore: r.trustScore ?? r.user?.reputation?.trustScore ?? null,
            // Honest routing state — nothing has been delivered to any agency.
            routing: { status: 'RECOMMENDED', delivered: false, estimatedReach: null, authoritiesNotified: [] }
          }));
        if (cancelled) return;
        setAlerts(critical);
        if (critical.length > 0 && !activeAlert) setActiveAlert(critical[0]);
      } catch (err) {
        if (!cancelled) setAlertsError('Critical reports could not be loaded. Check your connection and try again.');
      } finally {
        if (!cancelled) setAlertsLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, []);

  // Analyze routing when active alert changes
  useEffect(() => {
    if (!activeAlert) return;
    try {
      const analysis = routingService.analyzeAlert(activeAlert);
      setRoutingAnalysis(analysis);
    } catch (err) {
      console.warn('[AmberAlerts] routing analysis failed:', err.message);
      setRoutingAnalysis(null);
    }
  }, [activeAlert, routingService]);

  const handleRouteToAlert = (alert) => {
    if (!alert?.coordinates) return;
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          const { latitude, longitude } = position.coords;
          const url = `https://www.google.com/maps/dir/${latitude},${longitude}/${alert.coordinates.lat},${alert.coordinates.lng}`;
          window.open(url, '_blank');
        },
        (error) => {
          // Fallback - just open alert location
          const url = `https://www.google.com/maps?q=${alert.coordinates.lat},${alert.coordinates.lng}`;
          window.open(url, '_blank');
        }
      );
    }
  };

  const handleExecuteRouting = async () => {
    if (!routingAnalysis) return;
    try {
      const notifications = await routingService.executeRouting(routingAnalysis.routingPlan);
      flash(`Routing executed: ${notifications.length} notification(s) sent.`);
    } catch (err) {
      flash(`Routing failed: ${err.message}`);
    }
  };

  const handleShareAlert = (alert) => {
    const contactPhone = alert?.contact?.phone || 'Emergency line: 112';
    const shareText = `URGENT: ${alert.title}\n\nLocation: ${alert.location}\nDetails: ${alert.description}\n\nContact: ${contactPhone}\n\nPlease share this alert widely!`;
    
    if (navigator.share) {
      navigator.share({ title: alert.title, text: shareText, url: window.location.href }).catch(() => {});
    } else {
      navigator.clipboard?.writeText(shareText).then(() => flash('Alert details copied to clipboard!')).catch(() => {});
    }
  };

  const getSeverityColor = (severity) => {
    switch (severity) {
      case 'critical': return 'bg-red-500 text-white';
      case 'high': return 'bg-orange-500 text-white';
      case 'medium': return 'bg-yellow-500 text-white';
      case 'low': return 'bg-blue-500 text-white';
      default: return 'bg-gray-500 text-white';
    }
  };

  const getAlertIcon = (type) => {
    switch (type) {
      case 'amber': return <FaExclamationTriangle className="w-6 h-6" />;
      case 'environmental': return <FaShieldAlt className="w-6 h-6" />;
      case 'climate': return <FaBell className="w-6 h-6" />;
      default: return <FaExclamationTriangle className="w-6 h-6" />;
    }
  };

  const formatTimeAgo = (timestamp) => {
    const now = new Date();
    const alertTime = new Date(timestamp);
    const diffInMinutes = Math.floor((now - alertTime) / (1000 * 60));
    
    if (diffInMinutes < 60) {
      return `${diffInMinutes} minutes ago`;
    } else if (diffInMinutes < 1440) {
      return `${Math.floor(diffInMinutes / 60)} hours ago`;
    } else {
      return `${Math.floor(diffInMinutes / 1440)} days ago`;
    }
  };

  return (
    <div className="eco-page eco-fade-up">
      {flashMsg && (
        <div className="fixed top-4 right-4 z-50 bg-emerald-600 text-white px-6 py-3 rounded-lg shadow-lg text-sm font-medium">
          {flashMsg}
        </div>
      )}
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center space-x-3">
              <div className="bg-red-500 p-3 rounded-full">
                <FaExclamationTriangle className="w-8 h-8 text-white" />
              </div>
              <div>
                <h1 className="text-3xl font-bold text-gray-900">AMBER Alerts & Emergency Routing</h1>
                <p className="text-gray-600">Real-time emergency alerts and intelligent routing system</p>
              </div>
            </div>
            
            <div className="flex items-center space-x-4">
              <div className="flex items-center space-x-2">
                <label className="text-sm font-medium text-gray-700">Alert Radius:</label>
                <select
                  value={alertRadius}
                  onChange={(e) => setAlertRadius(parseInt(e.target.value))}
                  className="px-3 py-1 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500"
                >
                  <option value={1}>1 km</option>
                  <option value={5}>5 km</option>
                  <option value={10}>10 km</option>
                  <option value={25}>25 km</option>
                  <option value={50}>50 km</option>
                </select>
              </div>
              
              <button
                onClick={() => setNotifications(!notifications)}
                className={`px-4 py-2 rounded-lg font-medium transition-colors ${
                  notifications 
                    ? 'bg-emerald-600 text-white hover:bg-emerald-700' 
                    : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                }`}
              >
                <FaBell className="w-4 h-4 mr-2 inline" />
                {notifications ? 'Notifications On' : 'Notifications Off'}
              </button>
            </div>
          </div>
        </div>

        {/* Active Alert Banner */}
        {activeAlert && (
          <div className={`mb-8 p-6 rounded-lg border-2 ${getSeverityColor(activeAlert.severity)} bg-opacity-10 border-opacity-50`}>
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              {/* Alert Image */}
              <div className="lg:col-span-1">
                {activeAlert.image ? (
                  <img
                    src={activeAlert.image}
                    alt={activeAlert.title}
                    className="w-full h-48 object-cover rounded-lg"
                  />
                ) : (
                  <div className="w-full h-48 rounded-lg bg-gray-100 flex items-center justify-center text-gray-400 text-sm">
                    No field image attached
                  </div>
                )}
                <div className="mt-4 space-y-2">
                  <div className="flex items-center justify-between text-sm">
                    <span className="font-medium">Alert ID:</span>
                    <span className="font-mono">{activeAlert.id}</span>
                  </div>
                  <div className="flex items-center justify-between text-sm">
                    <span className="font-medium">Status:</span>
                    <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                      activeAlert.status === 'active' ? 'bg-red-100 text-red-800' : 'bg-yellow-100 text-yellow-800'
                    }`}>
                      {activeAlert.status.toUpperCase()}
                    </span>
                  </div>
                  <div className="flex items-center justify-between text-sm">
                    <span className="font-medium">Radius:</span>
                    <span>{activeAlert.radius} km</span>
                  </div>
                </div>
              </div>

              {/* Alert Details */}
              <div className="lg:col-span-2">
                <div className="flex items-start justify-between mb-4">
                  <div>
                    <h2 className="text-2xl font-bold text-gray-900 mb-2">{activeAlert.title}</h2>
                    <p className="text-gray-700 mb-4">{activeAlert.description}</p>
                  </div>
                  <div className={`px-3 py-1 rounded-full text-sm font-medium ${getSeverityColor(activeAlert.severity)}`}>
                    {activeAlert.severity.toUpperCase()}
                  </div>
                </div>

                {/* Quick Actions */}
                <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-6">
                  <button
                    onClick={() => handleRouteToAlert(activeAlert)}
                    className="flex flex-col items-center justify-center p-3 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors"
                  >
                    <FaRoute className="w-5 h-5 mb-1" />
                    <span className="text-xs">Get Directions</span>
                  </button>
                  
                  <button
                    onClick={() => handleShareAlert(activeAlert)}
                    className="flex flex-col items-center justify-center p-3 bg-green-500 text-white rounded-lg hover:bg-green-600 transition-colors"
                  >
                    <FaShareAlt className="w-5 h-5 mb-1" />
                    <span className="text-xs">Share Alert</span>
                  </button>
                  
                  <button
                    onClick={() => window.open(`tel:${activeAlert.contact?.phone || '112'}`)}
                    className="flex flex-col items-center justify-center p-3 bg-purple-500 text-white rounded-lg hover:bg-purple-600 transition-colors"
                  >
                    <FaPhone className="w-5 h-5 mb-1" />
                    <span className="text-xs">Call Emergency</span>
                  </button>
                  
                  <button
                    onClick={() => setShowMap(!showMap)}
                    className="flex flex-col items-center justify-center p-3 bg-gray-500 text-white rounded-lg hover:bg-gray-600 transition-colors"
                  >
                    <FaMapMarkerAlt className="w-5 h-5 mb-1" />
                    <span className="text-xs">View Map</span>
                  </button>
                  
                  <button
                    onClick={() => setShowRouting(!showRouting)}
                    className="flex flex-col items-center justify-center p-3 bg-red-500 text-white rounded-lg hover:bg-red-600 transition-colors"
                  >
                    <FaShieldAlt className="w-5 h-5 mb-1" />
                    <span className="text-xs">Authority Routing</span>
                  </button>
                </div>

                {/* Contact Information */}
                <div className="bg-white bg-opacity-50 rounded-lg p-4">
                  <h3 className="font-semibold text-gray-900 mb-3">Emergency Contact</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <p className="text-sm text-gray-600">Reported By:</p>
                      <p className="font-medium">{activeAlert.reportedBy}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-600">Phone:</p>
                      <p className="font-medium">{activeAlert.contact?.phone || 'Emergency line: 112'}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-600">Email:</p>
                      <p className="font-medium">{activeAlert.contact?.email || 'Not provided'}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-600">Last Updated:</p>
                      <p className="font-medium">{formatTimeAgo(activeAlert.lastSeen)}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Routing Analysis Section */}
        {showRouting && routingAnalysis && routingAnalysis.routingPlan && (
          <div className="mb-8 bg-white rounded-lg border-2 border-red-500 shadow-lg">
            <div className="p-6">
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center space-x-3">
                  <FaShieldAlt className="w-6 h-6 text-red-500" />
                  <h3 className="text-xl font-bold text-gray-900">Authority Routing Analysis</h3>
                  <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                    routingAnalysis.severity === 'critical' ? 'bg-red-100 text-red-800' : 
                    routingAnalysis.severity === 'high' ? 'bg-orange-100 text-orange-800' : 
                    'bg-yellow-100 text-yellow-800'
                  }`}>
                    {routingAnalysis.severity.toUpperCase()} SEVERITY
                  </span>
                </div>
                <button
                  onClick={handleExecuteRouting}
                  className="bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600 font-medium"
                >
                  Execute Emergency Routing
                </button>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Primary Authorities */}
                <div>
                  <h4 className="font-semibold text-gray-900 mb-3 flex items-center">
                    <FaAmbulance className="w-4 h-4 mr-2 text-red-500" />
                    Primary Response ({routingAnalysis.routingPlan.primary.length})
                  </h4>
                  <div className="space-y-2">
                    {routingAnalysis.routingPlan.primary.map((authority, index) => (
                      <div key={index} className="bg-red-50 border border-red-200 rounded-lg p-3">
                        <div className="flex items-center justify-between mb-2">
                          <span className="font-medium text-red-900">{authority.authority}</span>
                          <span className="text-xs bg-red-100 text-red-800 px-2 py-1 rounded-full">
                            {authority.responseTime}
                          </span>
                        </div>
                        <p className="text-sm text-gray-600 mb-1">{authority.role}</p>
                        <p className="text-xs text-gray-500">{authority.contact.phone}</p>
                        <div className="mt-2">
                          <p className="text-xs font-medium text-gray-700">Actions:</p>
                          <div className="flex flex-wrap gap-1 mt-1">
                            {authority.actions.slice(0, 2).map((action, i) => (
                              <span key={i} className="text-xs bg-white px-2 py-1 rounded border border-gray-200">
                                {action}
                              </span>
                            ))}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Secondary Authorities */}
                <div>
                  <h4 className="font-semibold text-gray-900 mb-3 flex items-center">
                    <FaUsers className="w-4 h-4 mr-2 text-orange-500" />
                    Secondary Support ({routingAnalysis.routingPlan.secondary.length})
                  </h4>
                  <div className="space-y-2">
                    {routingAnalysis.routingPlan.secondary.map((authority, index) => (
                      <div key={index} className="bg-orange-50 border border-orange-200 rounded-lg p-3">
                        <div className="flex items-center justify-between mb-2">
                          <span className="font-medium text-orange-900">{authority.authority}</span>
                          <span className="text-xs bg-orange-100 text-orange-800 px-2 py-1 rounded-full">
                            {authority.responseTime}
                          </span>
                        </div>
                        <p className="text-sm text-gray-600 mb-1">{authority.role}</p>
                        <p className="text-xs text-gray-500">{authority.contact.phone}</p>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Notification & Escalation */}
                <div>
                  <h4 className="font-semibold text-gray-900 mb-3 flex items-center">
                    <FaBell className="w-4 h-4 mr-2 text-blue-500" />
                    Notification Network ({routingAnalysis.routingPlan.notification.length + routingAnalysis.routingPlan.escalation.length})
                  </h4>
                  <div className="space-y-3">
                    <div>
                      <p className="text-sm font-medium text-gray-700 mb-2">Notification Authorities:</p>
                      <div className="space-y-1">
                        {routingAnalysis.routingPlan.notification.map((authority, index) => (
                          <div key={index} className="bg-blue-50 border border-blue-200 rounded p-2">
                            <div className="flex justify-between items-center">
                              <span className="text-sm font-medium text-blue-900">{authority.authority}</span>
                              <span className="text-xs text-gray-500">{authority.responseTime}</span>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                    <div>
                      <p className="text-sm font-medium text-gray-700 mb-2">Escalation Authorities:</p>
                      <div className="space-y-1">
                        {routingAnalysis.routingPlan.escalation.map((authority, index) => (
                          <div key={index} className="bg-gray-50 border border-gray-200 rounded p-2">
                            <div className="flex justify-between items-center">
                              <span className="text-sm font-medium text-gray-900">{authority.authority}</span>
                              <span className="text-xs text-gray-500">{authority.responseTime}</span>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Routing Summary */}
              <div className="mt-6 pt-6 border-t border-gray-200">
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                  <div className="text-center">
                    <p className="text-2xl font-bold text-red-500">{routingAnalysis.authorities.length}</p>
                    <p className="text-sm text-gray-600">Total Authorities</p>
                  </div>
                  <div className="text-center">
                    <p className="text-2xl font-bold text-orange-500">{routingAnalysis.routingPlan.primary.length}</p>
                    <p className="text-sm text-gray-600">Primary Response</p>
                  </div>
                  <div className="text-center">
                    <p className="text-2xl font-bold text-blue-500">{routingAnalysis.estimatedResponseTime}</p>
                    <p className="text-sm text-gray-600">Est. Response Time</p>
                  </div>
                  <div className="text-center">
                    <p className="text-2xl font-bold text-green-500">IMMEDIATE</p>
                    <p className="text-sm text-gray-600">Routing Priority</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Contact Information */}
        {activeAlert && (
          <div className="bg-white bg-opacity-50 rounded-lg p-4">
            <h3 className="font-semibold text-gray-900 mb-3">Emergency Contact</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <p className="text-sm text-gray-600">Reported By:</p>
                <p className="font-medium">{activeAlert.reportedBy}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Phone:</p>
                <p className="font-medium">{activeAlert.contact?.phone || 'Emergency line: 112'}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Email:</p>
                <p className="font-medium">{activeAlert.contact?.email || 'Not provided'}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Last Updated:</p>
                <p className="font-medium">{formatTimeAgo(activeAlert.lastSeen)}</p>
              </div>
            </div>
          </div>
        )}

        {/* Map View Toggle */}
        {showMap && activeAlert && (
          <div className="mb-8 bg-gray-100 rounded-lg p-4">
            <div className="bg-gray-300 h-96 rounded-lg flex items-center justify-center">
              <div className="text-center">
                <FaMapMarkerAlt className="w-16 h-16 text-gray-500 mx-auto mb-4" />
                <p className="text-gray-600 font-medium">Interactive Map View</p>
                <p className="text-sm text-gray-500 mt-2">Alert location: {activeAlert.location}</p>
                <p className="text-sm text-gray-500">Radius: {activeAlert.radius} km</p>
              </div>
            </div>
          </div>
        )}

        {/* All Alerts List */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2">
            <h3 className="text-xl font-semibold text-gray-900 mb-4">All Active Alerts</h3>
            {alertsLoading ? (
              <p className="text-gray-500 py-6">Loading critical reports…</p>
            ) : alertsError ? (
              <p className="text-red-600 py-6">{alertsError}</p>
            ) : alerts.length === 0 ? (
              <div className="p-6 rounded-lg border border-gray-200 bg-white">
                <p className="font-semibold text-gray-900 mb-2">No verified emergency alerts</p>
                <p className="text-sm text-gray-600">
                  EcoNet does not generate emergency alerts. No trusted emergency source is integrated on this
                  deployment, and there are currently no critical field reports requiring escalation. When a
                  verified source is connected, genuine alerts will appear here with their source and provenance.
                </p>
              </div>
            ) : (
            <div className="space-y-4">
              {alerts.map((alert) => (
                <div
                  key={alert.id}
                  onClick={() => setActiveAlert(alert)}
                  className={`p-4 rounded-lg border-2 cursor-pointer transition-all ${
                    activeAlert?.id === alert.id 
                      ? 'border-red-500 bg-red-50' 
                      : 'border-gray-200 bg-white hover:border-gray-300'
                  }`}
                >
                  <div className="flex items-start justify-between">
                    <div className="flex items-start space-x-3">
                      <div className={`p-2 rounded-full ${getSeverityColor(alert.severity)}`}>
                        {getAlertIcon(alert.type)}
                      </div>
                      <div className="flex-1">
                        <h4 className="font-semibold text-gray-900">{alert.title}</h4>
                        <p className="text-sm text-gray-600 mt-1">{alert.description}</p>
                        <div className="flex items-center space-x-4 mt-2 text-xs text-gray-500">
                          <span className="flex items-center">
                            <FaMapMarkerAlt className="w-3 h-3 mr-1" />
                            {alert.location}
                          </span>
                          <span className="flex items-center">
                            <FaClock className="w-3 h-3 mr-1" />
                            {formatTimeAgo(alert.lastSeen)}
                          </span>
                          <span className="flex items-center">
                            <FaEye className="w-3 h-3 mr-1" />
                            {alert.trustScore != null ? `trust ${alert.trustScore}` : 'trust unrated'}
                          </span>
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col items-end space-y-2">
                      <span className={`px-2 py-1 rounded-full text-xs font-medium ${getSeverityColor(alert.severity)}`}>
                        {alert.severity}
                      </span>
                      <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                        alert.status === 'active' ? 'bg-red-100 text-red-800' : 'bg-yellow-100 text-yellow-800'
                      }`}>
                        {alert.status}
                      </span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
            )}
          </div>

          {/* Routing Analytics */}
          <div className="lg:col-span-1">
            <h3 className="text-xl font-semibold text-gray-900 mb-4">Routing Analytics</h3>
            <div className="bg-white rounded-lg border border-gray-200 p-4">
              <div className="space-y-4">
              <div className="space-y-4">
                <div className="p-3 rounded-lg bg-amber-50 border border-amber-200 text-sm text-amber-900">
                  No agency delivery channel is configured on this deployment. The entries listed here are real
                  field reports marked RECOMMENDED for routing - none have been transmitted to an authority.
                </div>
                <div className="border-t pt-4">
                  <h4 className="font-medium text-gray-900 mb-3">Delivery status</h4>
                  <div className="space-y-2">
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-600">Critical reports loaded</span>
                      <span className="font-medium">{alerts.length}</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-600">Contacts delivered</span>
                      <span className="font-medium">0</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-600">Agency acknowledgment</span>
                      <span className="px-2 py-1 bg-gray-100 text-gray-700 rounded-full text-xs font-medium">Not integrated</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-gray-600">Emergency source feed</span>
                      <span className="px-2 py-1 bg-gray-100 text-gray-700 rounded-full text-xs font-medium">Not connected</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
    </div>
  );
}

export default AmberAlerts;
